version = 0.1
[default.deploy.parameters]
stack_name = "EmployeeManagementSystem"
resolve_s3 = true
s3_prefix = "EmployeeManagementSystem"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EnvName=\"\""
image_repositories = []
